openapi: '3.1.0'
info:
  title: STUDENT REGISTRATION FORM
  version: '2.0'
servers:
  - url: http://localhost:8087


paths:
  /StudentRegister:
    post:
      summary: Create a new student
      tags:
        - student
      description: studentcreated
      operationId: studentcreated
      responses:
        '201':
          description: studentCreate Sucessfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: studentCreateFailure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '409':
          description: student already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      requestBody:
        description: studentCreate
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/student"
        required: true

  /GetAllStudents:
    get:
      summary: Get a list of students
      tags:
        - student
      description:  Getstudent
      operationId: Getstudent
      responses:
        '201':
          description: Getstudent Sucessfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/student'
        '400':
          description: Getstudent UserCreateFailure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '409':
          description: student already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'

  
            

components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
  parameters:
    idParam:
      name: username
      in: query
      required: true
      schema:
        type: string
    

  schemas:
    ApiResponse:
      type: object
      description:  ResponseInStatusCode
      properties:
        code: 
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      required: 
        - message
            
    student:
      type: object
      properties:
        username:
          type: string
        password:
          type: string


