/* eslint-disable */
// tslint:disable
/**
 * STUDENT REGISTRATION FORM
 * 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface StudentApi {
	deletestudent: (id: string) => Promise<DeletestudentResponse>
	getGetAllStudents: () => Promise<GetGetAllStudentsResponse>
	getGetStudent: (id: string) => Promise<GetGetStudentResponse>
	studentcreated: (request: Api.Student) => Promise<StudentcreatedResponse>
	updatestudent: (id: string, request: Api.StudentUpdate) => Promise<UpdatestudentResponse>
}

export type DeletestudentResponse = Deletestudent201Response | Deletestudent400Response | Deletestudent409Response

export interface Deletestudent201Response {
	status: 201
	body: Api.ApiResponse
	headers?: never
}

export interface Deletestudent400Response {
	status: 400
	body: Api.ApiResponse
	headers?: never
}

export interface Deletestudent409Response {
	status: 409
	body: Api.ApiResponse
	headers?: never
}

export type GetGetAllStudentsResponse = GetGetAllStudents201Response | GetGetAllStudents400Response | GetGetAllStudents409Response

export interface GetGetAllStudents201Response {
	status: 201
	body: Api.Student[]
	headers?: never
}

export interface GetGetAllStudents400Response {
	status: 400
	body: Api.ApiResponse
	headers?: never
}

export interface GetGetAllStudents409Response {
	status: 409
	body: Api.ApiResponse
	headers?: never
}

export type GetGetStudentResponse = GetGetStudent201Response | GetGetStudent400Response | GetGetStudent409Response

export interface GetGetStudent201Response {
	status: 201
	body: Api.Student
	headers?: never
}

export interface GetGetStudent400Response {
	status: 400
	body: Api.ApiResponse
	headers?: never
}

export interface GetGetStudent409Response {
	status: 409
	body: Api.ApiResponse
	headers?: never
}

export type StudentcreatedResponse = Studentcreated201Response | Studentcreated400Response | Studentcreated409Response

export interface Studentcreated201Response {
	status: 201
	body: Api.ApiResponse
	headers?: never
}

export interface Studentcreated400Response {
	status: 400
	body: Api.ApiResponse
	headers?: never
}

export interface Studentcreated409Response {
	status: 409
	body: Api.ApiResponse
	headers?: never
}

export type UpdatestudentResponse = Updatestudent201Response | Updatestudent400Response | Updatestudent409Response

export interface Updatestudent201Response {
	status: 201
	body: Api.ApiResponse
	headers?: never
}

export interface Updatestudent400Response {
	status: 400
	body: Api.ApiResponse
	headers?: never
}

export interface Updatestudent409Response {
	status: 409
	body: Api.ApiResponse
	headers?: never
}

